# ===========================
# Monitor configuration
# ===========================
monitor = eDP-1,preferred,auto,1.6
monitor = HDMI-A-3,preferred,auto,1,mirror,eDP-1


# ===========================
# Keybindings
# ===========================
$mainMod = Alt
$subMod = Super

# Terminal
bind = $mainMod, Return, exec, kitty

# Anyrun
# bind = $mainMod, R, exec, anyrun

# walker
bind = $mainMod, R, exec, wofi --show drun

# File manager
bind = $mainMod, E, exec, nemo


# Window focus
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
bind = $mainMod, H, movefocus, l

# Window move
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, H, movewindow, l

# Window kill
bind = $mainMod, Q, killactive

# Lock screen
bind = $mainMod, F11, exec, hyprlock --no-fade-in

# Full screen
bind = $mainMod, F, fullscreen

# Grouping
bind = $mainMod, T, togglegroup
bind = $mainMod SHIFT, L, moveintogroup, l
bind = $mainMod SHIFT, H, moveintogroup, r
bind = $mainMod SHIFT, J, moveintogroup, d
bind = $mainMod SHIFT, K, moveintogroup, u
bind = $mainMod, L, changegroupactive, f
bind = $mainMod, H, changegroupactive, b
# bind = $mainMod SHIFT, Tab, cyclenext, prev tiled

# Workspace switch
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $subMod, l, workspace, +1
bind = $subMod, h, workspace, -1

# Move window across workspace
bind = $mainMod Shift, 1, movetoworkspace, 1
bind = $mainMod Shift, 2, movetoworkspace, 2
bind = $mainMod Shift, 3, movetoworkspace, 3
bind = $mainMod Shift, 4, movetoworkspace, 4
bind = $mainMod Shift, 5, movetoworkspace, 5
bind = $mainMod Shift, 6, movetoworkspace, 6
bind = $mainMod Shift, 7, movetoworkspace, 7
bind = $mainMod Shift, 8, movetoworkspace, 8
bind = $mainMod Shift, 9, movetoworkspace, 9
bind = $mainMod Shift, 0, movetoworkspace, 10

bind = $mainMod $subMod, l, movetoworkspace, +1
bind = $mainMod $subMod, h, movetoworkspace, -1


# Functional Keys
bind = , F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-
bind = , F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+
bind = Shift, F2, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%-
bind = Shift, F3, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%+
bind = , F1, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind = , F4, exec, brightnessctl set 5%-
bind = , F5, exec, brightnessctl set +5%
bind = Shift, F4, exec, brightnessctl set 1%-
bind = Shift, F5, exec, brightnessctl set +1%

# Touchpad
bind = $mainMod, Space, exec, ~/dotnix/resources/scripts/toggleTouchpad.sh

# Sway-NC
bind = $mainMod, N, exec, swaync-client -t

# Google
bind = $mainMod, G, exec, google-chrome-stable
bind = $mainMod, U, exec, google-chrome-stable --profile-directory="Default" # work profile
bind = $mainMod Shift, U, exec, google-chrome-stable --profile-directory="Profile 2" # university profile
bind = $mainMod, I, exec, google-chrome-stable --profile-directory="Profile 1" # main profile

# Asus laptop controls
bind = $mainMod, F7, exec, asusctl -n

# Screen shortcuts
bind = $mainMod, Print, exec, ~/dotnix/resources/scripts/screenshot.sh whole
bind = $mainMod, F11, exec, ~/dotnix/resources/scripts/screenshot.sh selection
bind = $mainMod, F8, exec, gpu-screen-recorder-gtk

# WireGuard
bind = $mainMod, F9, exec, ~/dotnix/resources/scripts/toggleVPN.sh
