# wallpaper {
#   monitor = DP-3
#   path = ~/dotnix/assets/nixland.png
#   fit_mode = cover
# }
# wallpaper {
#   monitor = DP-1
#   path = ~/dotnix/assets/nixland.png
#   fit_mode = cover
# }
wallpaper {
  monitor = eDP-1
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-3
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}
wallpaper {
  monitor =
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}

splash = false
ipc = true
