preload = ~/dotnix/assets/nixland.png

# wallpaper {
#   monitor = DP-3
#   path = ~/dotnix/assets/nixland.png
#   fit_mode = cover
# }
# wallpaper {
#   monitor = DP-1
#   path = ~/dotnix/assets/nixland.png
#   fit_mode = cover
# }
wallpaper {
  monitor = eDP-1
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-3
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}
wallpaper {
  monitor =
  path = ~/dotnix/assets/nixland.png
  fit_mode = cover
}

# wallpaper = DP-3, ~/dotnix/resources/assets/nixland.png
# wallpaper = DP-1, ~/dotnix/resources/assets/nixland.png
# wallpaper = eDP-1, ~/dotnix/resources/assets/nixland.png

splash = false;
ipc = true;
